# Generated by Django 3.2.5 on 2021-08-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='tbltasklist',
            field=models.ForeignKey(default=11000, on_delete=django.db.models.deletion.PROTECT, related_name='tbltasklist', to='TeamTask.tbltasklist'),
        ),
    ]
