# Generated by Django 3.2.5 on 2021-08-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0002_tblinvoicesummary_tbltasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='taskname',
            field=models.CharField(blank=True, db_column='taskname', max_length=255, null=True),
        ),
    ]
