# Generated by Django 3.2.5 on 2021-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0003_tblinvoicesummary_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='clientcompanyname',
            field=models.CharField(blank=True, db_column='clientcompanyname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='clientname',
            field=models.CharField(blank=True, db_column='clientname', max_length=255, null=True),
        ),
    ]
