# Generated by Django 3.1.1 on 2021-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0004_auto_20210809_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.CharField(blank=True, max_length=255, null=True)),
                ('isvisible', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_company',
                'managed': True,
            },
        ),
    ]
