# Generated by Django 3.1.1 on 2021-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0005_tblcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompany',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tblcompany',
            name='isvisible',
            field=models.BooleanField(default=True),
        ),
    ]
