# Generated by Django 3.1.1 on 2021-09-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0006_auto_20210909_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltasklist',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='TeamTask.tblcompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbltasklist',
            name='companyname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
