# Generated by Django 3.2.5 on 2021-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0007_auto_20210909_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltransaction',
            name='clientbalance',
        ),
        migrations.RemoveField(
            model_name='tbltransaction',
            name='invoicebalance',
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='companyid',
            field=models.CharField(blank=True, default='1', max_length=250, null=True),
        ),
    ]
