# Generated by Django 3.1.1 on 2021-09-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0008_auto_20210917_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltransactionoverview',
            old_name='ClientBalance',
            new_name='companyid',
        ),
        migrations.RemoveField(
            model_name='tbltransactionoverview',
            name='InvoiceBalance',
        ),
    ]
