# Generated by Django 3.2.5 on 2021-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0009_auto_20210918_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltransacttable',
            old_name='clientbalance',
            new_name='companyid',
        ),
        migrations.RemoveField(
            model_name='tbltransacttable',
            name='invoicebalance',
        ),
        migrations.AddField(
            model_name='tbltransactionoverview',
            name='Amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbltransaction',
            name='companyid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
