# Generated by Django 3.2.5 on 2021-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0011_tblcompany_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='invocieid',
            field=models.CharField(blank=True, db_column='invocieid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='isMoved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tblcompany',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
