# Generated by Django 3.2.5 on 2021-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0013_rename_invocieid_tblinvoicesummary_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoicesummary',
            name='invoiceid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
