# Generated by Django 3.2.5 on 2021-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0014_alter_tblinvoicesummary_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='companyid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
