# Generated by Django 3.2.5 on 2021-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0015_tblinvoicesummary_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoicesummary',
            name='companyid',
            field=models.CharField(blank=True, default='1', max_length=255, null=True),
        ),
    ]
