# Generated by Django 3.2.5 on 2021-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0016_alter_tblinvoicesummary_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompany',
            name='companycode',
            field=models.IntegerField(default=0),
        ),
    ]
