# Generated by Django 3.2.5 on 2021-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0017_tblcompany_companycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltasklist',
            name='invoiceid',
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='originalcompanyid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='originalinvoiceid',
            field=models.IntegerField(default=0),
        ),
    ]
