# Generated by Django 3.2.5 on 2021-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0018_auto_20211002_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoicesummary',
            name='invoiceid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
