# Generated by Django 3.2.5 on 2021-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0019_alter_tblinvoicesummary_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransaction',
            name='originalcompanyid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='originalinvoiceid',
            field=models.IntegerField(default=0),
        ),
    ]
