# Generated by Django 3.2.5 on 2021-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0020_auto_20211005_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyid', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(blank=True, max_length=100, null=True)),
                ('accountno', models.CharField(blank=True, max_length=100, null=True)),
                ('upi', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_bank',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='referenceno',
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='pmtmode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='pmtreference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
