# Generated by Django 3.2.5 on 2021-10-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0021_auto_20211011_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='clientcompanyname',
        ),
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='clientname',
        ),
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='taskname',
        ),
    ]
