# Generated by Django 3.2.5 on 2021-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0022_auto_20211016_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
