# Generated by Django 3.2.5 on 2021-10-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0023_tblbank_ifsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblbank',
            name='companyid',
        ),
        migrations.AddField(
            model_name='tblbank',
            name='companydetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='companydetails', to='TeamTask.tblcompany'),
        ),
    ]
