# Generated by Django 3.2.5 on 2021-10-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0024_auto_20211018_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbank',
            name='companydetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TeamTask.tblcompany'),
        ),
    ]
