# Generated by Django 3.2.5 on 2021-10-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0025_alter_tblbank_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbank',
            name='companydetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companydetails_id', to='TeamTask.tblcompany'),
        ),
    ]
