# Generated by Django 3.1.1 on 2021-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0026_alter_tblbank_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransactionoverview',
            name='Paymentmode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbltransactionoverview',
            name='ReferenceNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbltransacttable',
            name='pmtmode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbltransacttable',
            name='pmtreference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
