# Generated by Django 3.2.5 on 2021-11-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0028_tblpurchaseorder_tblpurchasestocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchasestocks',
            name='purchasestockid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasestock', to='TeamTask.tblpurchaseorder'),
        ),
    ]
