# Generated by Django 3.2.5 on 2021-11-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0029_alter_tblpurchasestocks_purchasestockid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpurchasestocks',
            name='purchaseid',
        ),
    ]
