# Generated by Django 3.2.5 on 2021-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0030_remove_tblpurchasestocks_purchaseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
