# Generated by Django 3.2.5 on 2021-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0031_tblpurchasestocks_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchasestocks',
            old_name='companyid',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='tblpurchasestocks',
            name='status',
        ),
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
