# Generated by Django 3.2.5 on 2021-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0032_auto_20211109_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='deliverynoteid',
            field=models.IntegerField(default=0),
        ),
    ]
