# Generated by Django 3.1.1 on 2021-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0036_auto_20211113_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblinvoicesummary',
            old_name='invoiceid',
            new_name='deliverynoteid',
        ),
        migrations.RenameField(
            model_name='tblinvoicesummary',
            old_name='originalinvoiceid',
            new_name='originaldeliverynoteid',
        ),
        migrations.RenameField(
            model_name='tbltransaction',
            old_name='invoiceid',
            new_name='deliverynoteid',
        ),
        migrations.RenameField(
            model_name='tbltransaction',
            old_name='originalinvoiceid',
            new_name='originaldeliverynoteid',
        ),
        # migrations.RenameField(
        #     model_name='tbltransacttable',
        #     old_name='invoiceid',
        #     new_name='deliverynoteid',
        # ),
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='quotationid',
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='companyinvoiceid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='roundoff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='cgstdiscount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='cgstdiscountpercentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='productcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='sgstdiscount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='sgstdiscountpercentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
