# Generated by Django 3.1.1 on 2021-11-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0037_auto_20211117_1805'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='tbltransacttable',
        #     old_name='invoiceid',
        #     new_name='deliverynoteid',
        # ),
    ]
