# Generated by Django 3.2.5 on 2021-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0038_auto_20211118_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPurchaseUserrequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('purchasestocksid', models.CharField(blank=True, max_length=100, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_purchase_userrequest',
                'managed': True,
            },
        ),
        # migrations.RenameField(
        #     model_name='tbltransacttable',
        #     old_name='invoiceid',
        #     new_name='deliverynoteid',
        # ),
    ]
