# Generated by Django 3.2.5 on 2021-11-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0039_auto_20211123_1743'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='tblpurchaseuserrequest',
        #     old_name='purchasestocksid',
        #     new_name='purchaseorderid',
        # ),
        # migrations.RenameField(
        #     model_name='tbltransacttable',
        #     old_name='invoiceid',
        #     new_name='deliverynoteid',
        # ),
    ]
