# Generated by Django 3.2.5 on 2021-11-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0041_auto_20211126_1611'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tblpurchaseuserrequest',
        #     name='purchasestocksid',
        # ),
        # migrations.RemoveField(
        #     model_name='tbltransacttable',
        #     name='invoiceid',
        # ),
        # migrations.AddField(
        #     model_name='tblpurchaseuserrequest',
        #     name='purchaseorderid',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransacttable',
        #     name='deliverynoteid',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
    ]
