# Generated by Django 3.2.5 on 2021-11-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0042_auto_20211126_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchasestocks',
            old_name='purchasestockid',
            new_name='purchasesorderid',
        ),
    ]
