# Generated by Django 3.1.1 on 2021-12-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0043_rename_purchasestockid_tblpurchasestocks_purchasesorderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblClientGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_clientgroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStockGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_stockgroup',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblclient',
            name='clientgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clientgroup', to='TeamTask.tblclientgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstock',
            name='stockgroup',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='stockgroup', to='TeamTask.tblstockgroup'),
            preserve_default=False,
        ),
    ]
