# Generated by Django 3.1.1 on 2021-12-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0044_auto_20211201_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblclient',
            name='clientgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientgroup', to='TeamTask.tblclientgroup'),
        ),
        migrations.AlterField(
            model_name='tblstock',
            name='stockgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockgroup', to='TeamTask.tblstockgroup'),
        ),
    ]
