# Generated by Django 3.2.5 on 2021-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0044_auto_20211201_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblInventorytransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('convertionstockname', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=100, null=True)),
                ('purchaseorderid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_inventorytransaction',
                'managed': (True,),
            },
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='invoiceno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='remaining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
