# Generated by Django 3.1.1 on 2021-12-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0045_auto_20211202_1334'),
        ('TeamTask', '0045_auto_20211202_1448'),
    ]

    operations = [
    ]
