# Generated by Django 3.1.1 on 2021-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0046_merge_20211206_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPurchaseinvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('purchaseinvocieno', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_purchaseivoice',
                'managed': (True,),
            },
        ),
    ]
