# Generated by Django 3.2.9 on 2021-12-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0047_tblpurchaseinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstock',
            name='cgstdiscount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblstock',
            name='sgstdiscount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
