# Generated by Django 3.2.9 on 2021-12-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0048_auto_20211207_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstock',
            old_name='cgstdiscount',
            new_name='cgstpercentange',
        ),
        migrations.RenameField(
            model_name='tblstock',
            old_name='sgstdiscount',
            new_name='sgstpercentage',
        ),
    ]
