# Generated by Django 3.2.9 on 2021-12-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0050_rename_cgstpercentange_tblstock_cgstpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchasestocks',
            name='received',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
