# Generated by Django 3.2.9 on 2021-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0051_alter_tblpurchasestocks_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstock',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblstock',
            name='liquid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstock',
            name='cgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblstock',
            name='sgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
