# Generated by Django 3.2.9 on 2021-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0052_auto_20211207_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstock',
            name='length',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstock',
            name='liquid',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
