# Generated by Django 3.2.9 on 2021-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0053_auto_20211207_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='length',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
