# Generated by Django 3.2.9 on 2021-12-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0054_tblinventorytransaction_length'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblpurchaseinvoice',
            table='tbl_purchaseinvoice',
        ),
    ]
