# Generated by Django 3.2.9 on 2021-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0055_alter_tblpurchaseinvoice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='receivedquantity',
            field=models.IntegerField(blank=True, default=0, max_length=100),
        ),
    ]
