# Generated by Django 3.2.9 on 2021-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0056_tblinventorytransaction_receivedquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='receivedquantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
