# Generated by Django 3.2.9 on 2021-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0057_alter_tblinventorytransaction_receivedquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
       
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='cgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='sgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
        
    ]
