# Generated by Django 3.2.5 on 2021-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0059_auto_20211209_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='purchaseinvoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoice', to='TeamTask.tblpurchasebillinvoice'),
            preserve_default=False,
        ),
    ]
