# Generated by Django 3.2.9 on 2021-12-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0060_tblinventorytransaction_purchaseinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='purchaseinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoice', to='TeamTask.tblpurchasebillinvoice'),
        ),
    ]
