# Generated by Django 3.2.5 on 2021-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0061_alter_tblinventorytransaction_purchaseinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchno', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_batch',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buildingno', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': (True,),
            },
        ),
    ]
