# Generated by Django 3.2.5 on 2021-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0063_auto_20211210_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
