# Generated by Django 3.2.9 on 2021-12-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0064_alter_tblinventorytransaction_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchaseuserrequest',
            old_name='purchasestocksid',
            new_name='purchaseorderid',
        ),
        migrations.RenameField(
            model_name='tbltransacttable',
            old_name='invoiceid',
            new_name='deliverynoteid',
        ),
    ]
