# Generated by Django 3.2.5 on 2021-12-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0065_tblsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSalestransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=100, null=True)),
                ('purchaseorderid', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('cgstpercentage', models.CharField(blank=True, default=0, max_length=100)),
                ('sgstpercentage', models.CharField(blank=True, default=0, max_length=100)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('batch', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('location', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('salesinvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesinvoice', to='TeamTask.tblsales')),
            ],
            options={
                'db_table': 'tbl_salestransaction',
                'managed': (True,),
            },
        ),
    ]
