# Generated by Django 3.2.9 on 2021-12-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0065_auto_20211214_1742'),
        ('TeamTask', '0066_tblsalestransaction'),
    ]

    operations = [
    ]
