# Generated by Django 3.2.9 on 2021-12-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0067_merge_20211215_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=255, null=True)),
                ('purchasefrom', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('paid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('purchaseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseid', to='TeamTask.tblpurchasebillinvoice')),
            ],
            options={
                'db_table': 'tbl_expenses',
                'managed': (True,),
            },
        ),
    ]
