# Generated by Django 3.2.9 on 2021-12-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0069_alter_tblexpenses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblexpenses',
            name='purchaseid',
        ),
        migrations.AddField(
            model_name='tblexpenses',
            name='purchaseexpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseexpense', to='TeamTask.tblpurchasebillinvoice'),
        ),
    ]
