# Generated by Django 3.2.9 on 2021-12-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0070_auto_20211216_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='invoiceno',
        ),
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='length',
        ),
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='username',
        ),
    ]
