# Generated by Django 3.2.9 on 2021-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0071_auto_20211216_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='purchaseorderid',
        ),
    ]
