# Generated by Django 3.2.5 on 2021-12-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0073_tblsalesrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='salesid',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
