# Generated by Django 3.2.5 on 2021-12-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0074_tblinventorytransaction_salesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='salesid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
