# Generated by Django 3.2.9 on 2021-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0075_alter_tblinventorytransaction_salesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsalestransaction',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
