# Generated by Django 3.2.9 on 2021-12-23 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0076_tblsalestransaction_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='salesinvoice',
        ),
        migrations.AddField(
            model_name='tblsalestransaction',
            name='salestansaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salestransaction', to='TeamTask.tblsales'),
        ),
    ]
