# Generated by Django 3.2.5 on 2021-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0077_auto_20211223_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalestransaction',
            name='salestansaction',
        ),
        migrations.AddField(
            model_name='tblsalestransaction',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='TeamTask.tblsales'),
        ),
    ]
