# Generated by Django 3.2.5 on 2021-12-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0078_auto_20211223_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='batch',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
