# Generated by Django 3.2.5 on 2021-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0080_tblvouchermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsales',
            name='roundoff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
