# Generated by Django 3.2.5 on 2021-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0081_tblsales_roundoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='gsttype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
