# Generated by Django 3.2.9 on 2021-12-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0082_auto_20211231_1547'),
        ('TeamTask', '0082_tblpurchasestocks_gsttype'),
    ]

    operations = [
    ]
