# Generated by Django 3.2.9 on 2021-12-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0083_merge_20211231_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblvoucherdetails',
            options={'managed': (True,)},
        ),
        migrations.AlterModelTable(
            name='tblvoucherdetails',
            table='tbl_voucherdetails',
        ),
    ]
