# Generated by Django 3.2.5 on 2022-01-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0085_tblpurchasebillinvoice_roundoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSalesdispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('salesinvoiceno', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('roundoff', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_salesdispatch',
                'managed': (True,),
            },
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='salesdispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesdispatch', to='TeamTask.tblsalesdispatch'),
        ),
    ]
