# Generated by Django 3.2.9 on 2022-01-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0086_auto_20220103_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblvoucherdetails',
            old_name='name',
            new_name='voucherreferencetype',
        ),
        migrations.RenameField(
            model_name='tblvoucherdetails',
            old_name='status',
            new_name='vouchertype',
        ),
        migrations.RemoveField(
            model_name='tblvoucherdetails',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='tblvoucherdetails',
            name='salesid',
        ),
        migrations.AddField(
            model_name='tblsales',
            name='advancereceived',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='TeamTask.tblvouchermanagement'),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='voucherreferencetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='vouchertype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
