# Generated by Django 3.2.9 on 2022-01-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0087_auto_20220104_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='advancepaid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
