# Generated by Django 3.2.9 on 2022-01-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0088_tblpurchaseorder_advancepaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalesdispatch',
            name='salesinvoiceno',
        ),
    ]
