# Generated by Django 3.2.9 on 2022-01-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0090_tbldetailstype'),
        ('TeamTask', '0091_auto_20220104_1742'),
    ]

    operations = [
    ]
