# Generated by Django 3.2.9 on 2022-01-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0092_merge_0090_tbldetailstype_0091_auto_20220104_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='advanceused',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblsales',
            name='advanceused',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
