# Generated by Django 3.2.9 on 2022-01-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0094_auto_20220106_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblsalesdispatch',
            old_name='receivedamount',
            new_name='amountreceived',
        ),
    ]
