# Generated by Django 3.2.9 on 2022-01-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0095_rename_receivedamount_tblsalesdispatch_amountreceived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblvouchermanagement',
            old_name='cashmode',
            new_name='paymentmode',
        ),
        migrations.RenameField(
            model_name='tblvouchermanagement',
            old_name='detailsubtype',
            new_name='vouchersubreferencetype',
        ),
        migrations.RenameField(
            model_name='tblvouchermanagement',
            old_name='detailtype',
            new_name='vouchersubtype',
        ),
    ]
