# Generated by Django 3.2.9 on 2022-01-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0097_alter_tblvouchermanagement_amount'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tblclient',
        #     name='gstnumber',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tblclient',
        #     name='pannumber',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransactionoverview',
        #     name='voucher_id',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransactionoverview',
        #     name='voucherreferencetype',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransactionoverview',
        #     name='vouchertype',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransacttable',
        #     name='voucher_id',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransacttable',
        #     name='voucherreferencetype',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tbltransacttable',
        #     name='vouchertype',
        #     field=models.CharField(blank=True, max_length=250, null=True),
        # ),
    ]
