# Generated by Django 3.2.9 on 2022-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0098_auto_20220108_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbllocation',
            name='godown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
