# Generated by Django 3.2.5 on 2022-01-10 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0099_tbllocation_godown'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPurchasebillstocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('cgstdiscount', models.CharField(blank=True, max_length=100, null=True)),
                ('sgstdiscount', models.CharField(blank=True, max_length=100, null=True)),
                ('cgstdiscountpercentage', models.CharField(blank=True, max_length=100, null=True)),
                ('sgstdiscountpercentage', models.CharField(blank=True, max_length=100, null=True)),
                ('gsttype', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('received', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('remaining', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=100, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='TeamTask.tblpurchasebillinvoice')),
            ],
            options={
                'db_table': 'tbl_purchasebillstocks',
                'managed': True,
            },
        ),
    ]
