# Generated by Django 3.2.5 on 2022-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0100_tblpurchasebillstocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchasebillstocks',
            old_name='cgstdiscount',
            new_name='purchaseorderid',
        ),
        migrations.RenameField(
            model_name='tblpurchasebillstocks',
            old_name='cgstdiscountpercentage',
            new_name='stockname',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='gsttype',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='invoiceno',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='received',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='sgstdiscount',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='sgstdiscountpercentage',
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='batch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='cgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='length',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='sgstpercentage',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblpurchasebillstocks',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tblpurchasebillstocks',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tblpurchasebillstocks',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
