# Generated by Django 3.2.5 on 2022-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0101_auto_20220110_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='invoiceno',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
