# Generated by Django 3.2.9 on 2022-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0102_tblpurchasebillstocks_invoiceno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='length',
        ),
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='location',
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='received',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
