# Generated by Django 3.2.9 on 2022-01-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0103_auto_20220111_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='received',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='length',
        ),
        migrations.RemoveField(
            model_name='tblpurchasebillstocks',
            name='location',
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='batch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='length',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpurchasebillstocks',
            name='received',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
