# Generated by Django 3.2.9 on 2022-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0105_rename_batch_tblinventorytransaction_lotno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='batch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='lotno',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
