# Generated by Django 3.2.5 on 2022-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0106_auto_20220111_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchasebillstocks',
            name='purchaseorderid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
