# Generated by Django 3.2.5 on 2022-01-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0107_alter_tblpurchasebillstocks_purchaseorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchasebillstocks',
            name='purchaseorderid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
