# Generated by Django 3.2.9 on 2022-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0108_alter_tblpurchasebillstocks_purchaseorderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseorder',
            name='deliverydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblsales',
            name='dispatchdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
