# Generated by Django 3.2.5 on 2022-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0109_auto_20220112_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='batch',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='lotno',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
