# Generated by Django 3.2.5 on 2022-01-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0110_auto_20220112_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='lotno',
        ),
    ]
