# Generated by Django 3.1.1 on 2022-01-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0112_delete_tbltransactionoverview'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='TblTransactTable',
        # ),
    ]
