# Generated by Django 3.2.5 on 2022-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0112_delete_tbltransactionoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsales',
            name='paymentterms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
