# Generated by Django 3.1.1 on 2022-01-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0113_delete_tbltransacttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblSummarizedBalance',
        ),
    ]
