# Generated by Django 3.1.1 on 2022-01-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0113_tblsales_paymentterms'),
        ('TeamTask', '0114_delete_tblsummarizedbalance'),
    ]

    operations = [
    ]
