# Generated by Django 3.1.1 on 2022-01-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0115_merge_20220118_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='task_invoiceno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_invoiceno', to='TeamTask.tblinvoicesummary'),
        ),
    ]
