# Generated by Django 3.2.9 on 2022-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0117_tblinventorytransaction_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinventorytransaction',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblpurchasestocks',
            name='received',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
