# Generated by Django 3.1.1 on 2022-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0119_auto_20220122_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tblinventorytransaction',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
