# Generated by Django 3.2.9 on 2022-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0120_auto_20220122_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstock',
            name='hsncode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
