# Generated by Django 3.2.5 on 2022-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0120_auto_20220122_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoicesummary',
            name='tbltasklist',
            field=models.ForeignKey(blank=True, default=11000, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tbltasklist', to='TeamTask.tbltasklist'),
        ),
    ]
