# Generated by Django 3.2.9 on 2022-01-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0122_tblsalesdispatch_tblinvoicesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='salesorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder', to='TeamTask.tblsales'),
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='vehiclenumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='salesorderid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
