# Generated by Django 3.2.5 on 2022-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0121_alter_tblinvoicesummary_tbltasklist'),
        ('TeamTask', '0123_auto_20220125_1306'),
    ]

    operations = [
    ]
