# Generated by Django 3.2.5 on 2022-01-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0124_merge_20220125_1601'),
        # //('TeamTask', '0125_auto_20220125_1802'),
    ]

    operations = [
    ]
