# Generated by Django 3.2.5 on 2022-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0126_merge_20220128_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='invoicetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
