# Generated by Django 3.2.9 on 2022-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0127_tblinvoicesummary_invoicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsalesdispatch',
            name='tblinvoicesummary',
        ),
        migrations.AddField(
            model_name='tblpurchasestocks',
            name='hsncode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblsalesdispatch',
            name='tblinvoicesummary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
