# Generated by Django 3.2.5 on 2022-01-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0128_auto_20220128_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='salesdispatch',
        ),
        migrations.DeleteModel(
            name='TblSalesdispatch',
        ),
    ]
