# Generated by Django 3.1.1 on 2022-01-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0130_auto_20220129_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblDetailstype',
        ),
    ]
