# Generated by Django 3.2.9 on 2022-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0132_tblvouchergroups_tblvouchertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblvouchertypes',
            name='isvisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tblvouchergroups',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tblvouchergroups',
            name='isvisible',
            field=models.BooleanField(default=False),
        ),
    ]
