# Generated by Django 3.2.9 on 2022-01-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0133_auto_20220131_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblvouchergroups',
            options={'managed': (True,)},
        ),
        migrations.AlterModelOptions(
            name='tblvouchertypes',
            options={'managed': (True,)},
        ),
        migrations.AlterModelTable(
            name='tblvouchergroups',
            table='tbl_vouchergroup',
        ),
        migrations.AlterModelTable(
            name='tblvouchertypes',
            table='tbl_voucherdatatype',
        ),
    ]
