# Generated by Django 3.2.9 on 2022-01-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0134_auto_20220131_1253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblvouchertypes',
            table='tbl_vouchertype',
        ),
    ]
