# Generated by Django 3.2.9 on 2022-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0135_alter_tblvouchertypes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompany',
            name='isgst',
            field=models.BooleanField(default=True),
        ),
    ]
