# Generated by Django 3.2.9 on 2022-02-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0137_auto_20220201_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='clientgroupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientgroupid', to='TeamTask.tblclientgroup'),
        ),
    ]
