# Generated by Django 3.2.9 on 2022-02-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0137_auto_20220204_1127'),
        ('TeamTask', '0138_tblinvoicesummary_clientgroupid'),
    ]

    operations = [
    ]
