# Generated by Django 3.2.5 on 2022-02-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0139_merge_20220205_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblQuotationrequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('roundoff', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('advancereceived', models.CharField(blank=True, default=0, max_length=100)),
                ('advanceused', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentterms', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatchdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_quotationrequest',
                'managed': (True,),
            },
        ),
        # migrations.RemoveField(
        #     model_name='tblsalesrequest',
        #     name='client',
        # ),
        # migrations.RemoveField(
        #     model_name='tblsalesrequest',
        #     name='company',
        # ),
        migrations.CreateModel(
            name='TblQuotationtransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('productcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('usedqty', models.CharField(blank=True, default=0, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('cgstpercentage', models.CharField(blank=True, default=0, max_length=100)),
                ('sgstpercentage', models.CharField(blank=True, default=0, max_length=100)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('isdeleted', models.BooleanField(default=False)),
                ('hsncode', models.CharField(blank=True, max_length=100, null=True)),
                ('salesquotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesquotation', to='TeamTask.tblquotationrequest')),
            ],
            options={
                'db_table': 'tbl_quotationtransaction',
                'managed': (True,),
            },
        ),
    ]
