# Generated by Django 3.2.9 on 2022-02-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0140_auto_20220205_1305'),
        ('TeamTask', '0140_auto_20220205_1405'),
    ]

    operations = [
    ]
