# Generated by Django 3.2.9 on 2022-02-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0142_auto_20220207_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinventorytransaction',
            name='task_invoiceno',
        ),
        migrations.AddField(
            model_name='tblsalestransaction',
            name='task_invoiceno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_invoiceno', to='TeamTask.tblinvoicesummary'),
        ),
    ]
