# Generated by Django 3.2.9 on 2022-02-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0143_auto_20220207_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransaction',
            name='client_groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_groupid', to='TeamTask.tblclientgroup'),
        ),
    ]
