# Generated by Django 3.2.5 on 2022-02-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0144_tbltransaction_client_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchasebillinvoice',
            name='invoicedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblquotationrequest',
            name='phoneno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblsales',
            name='deliveryaddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
