# Generated by Django 3.2.9 on 2022-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0145_auto_20220216_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUnitType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_unittype',
                'managed': True,
            },
        ),
    ]
