# Generated by Django 3.2.9 on 2022-02-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0146_tblunittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
