# Generated by Django 3.2.9 on 2022-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0148_auto_20220218_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='purchase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
