# Generated by Django 3.2.9 on 2022-02-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0151_alter_users_reload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTaskProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientid', models.CharField(blank=True, max_length=255, null=True)),
                ('clientname', models.CharField(blank=True, max_length=255, null=True)),
                ('plantype', models.CharField(blank=True, max_length=255, null=True)),
                ('subclient', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('drawingtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('taskname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_taskprojects',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='TblTaskSubProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignto', models.CharField(blank=True, max_length=255, null=True)),
                ('plantype', models.CharField(blank=True, max_length=255, null=True)),
                ('subclient', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('drawingtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('taskname', models.CharField(blank=True, max_length=255, null=True)),
                ('taskproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taskproject', to='TeamTask.tbltaskprojects')),
            ],
            options={
                'db_table': 'tbl_tasksubprojects',
                'managed': (True,),
            },
        ),
    ]
