# Generated by Django 3.2.9 on 2022-02-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0152_tbltaskprojects_tbltasksubprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientid', models.CharField(blank=True, max_length=255, null=True)),
                ('clientname', models.CharField(blank=True, max_length=255, null=True)),
                ('subclient', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('projectname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_projects',
                'managed': (True,),
            },
        ),
        migrations.RemoveField(
            model_name='tbltasksubprojects',
            name='taskproject',
        ),
        migrations.DeleteModel(
            name='TblTaskProjects',
        ),
        migrations.DeleteModel(
            name='TblTaskSubProjects',
        ),
        migrations.AddField(
            model_name='tbltasklist',
            name='taskproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taskproject', to='TeamTask.tblprojects'),
        ),
    ]
