# Generated by Django 3.2.9 on 2022-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0154_tbltasklist_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblprojects',
            name='totalamount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbltasklist',
            name='totalamount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='initial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
