# Generated by Django 3.2.9 on 2022-04-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0155_auto_20220311_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='projectid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectid', to='TeamTask.tblprojects'),
        ),
        migrations.AddField(
            model_name='tblprojects',
            name='invoiceid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbltasklist',
            name='invoiceidno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
