# Generated by Django 3.2.5 on 2022-04-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0156_auto_20220419_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblinvoicesummary',
            name='projectid',
        ),
    ]
