# Generated by Django 3.2.5 on 2022-04-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0157_remove_tblinvoicesummary_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='project',
            field=models.ForeignKey(blank=True, default=11000, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='TeamTask.tblprojects'),
        ),
    ]
