# Generated by Django 3.2.5 on 2022-04-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0158_tblinvoicesummary_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinvoicesummary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='TeamTask.tblprojects'),
        ),
    ]
