# Generated by Django 3.2.5 on 2022-06-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamTask', '0161_auto_20220607_1035'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='TblJoinInvoicesummary',
        # ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='invoice_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_company', to='TeamTask.tblcompany'),
        ),
        migrations.AddField(
            model_name='tblinvoicesummary',
            name='invoicesummaryclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicesummaryclient', to='TeamTask.tblclient'),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_id', to='TeamTask.tblcompany'),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='transaction_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_client', to='TeamTask.tblclient'),
        ),
        migrations.AddField(
            model_name='tbltransaction',
            name='transactiontask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactiontask', to='TeamTask.tbltasklist'),
        ),
        migrations.AlterField(
            model_name='tbltransaction',
            name='companyid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # migrations.AlterField(
        #     model_name='tbltransaction',
        #     name='description',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        migrations.AlterField(
            model_name='tbltransaction',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='TeamTask.users'),
        ),
        migrations.AlterField(
            model_name='tbltransaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='TeamTask.tblvouchermanagement'),
        ),
        migrations.AlterField(
            model_name='tblworktimetable',
            name='clientName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblworktimetable',
            name='maintaskname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblworktimetable',
            name='subtaskname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
